fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [file, python]
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
    - id: ruff-check
      name: ruff-check
      entry: poetry run ruff check
      language: system
      types: [ file, python ]
    - id: pytest
      name: pytest
      entry: poetry run pytest tests/
      language: system
      types: [ file, python ]